version: '3.8'

services:
  # 1. A sua Aplicação Spring Boot
  app:
    build: .
    container_name: meeting_scheduler_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/scheduler
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  # 2. O Banco de Dados (Já estava ótimo)
  postgres:
    image: postgres:15-alpine
    container_name: scheduler_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d scheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: