spring:
  application:
    name: meeting-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false